### ISSUE TITLE
Unmarshal does not work if a field name differs from related annotation name

### ISSUE THREAD

**Issue by alexey-igrychev** [ghodss/yaml#59]
**Yaml**
```
apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/dockerconfigjson
```

**Struct**
```
type Template struct {
  Version string `yaml:"apiVersion,omitempty"`
  Kind    string `yaml:"kind,omitempty"`
}
```

After unmarshaling (`yaml.Unmarshal`) the field _Version_ is empty. 
If the field is renamed to _ApiVersion_ unmarshal works properly.
